### ISSUE TITLE
Mac OS Keybinding is overlapping toggle_regex function

### ISSUE THREAD

**Issue by jonarrien** [braindamageinc/SublimeHttpRequester#28]
When using Sublime's builtin incremental search, the same keybinding is used for toggling reggex patterns in the search field(Super+Alt+R)

I've just add this key bindings to my User keybindings file to take effect again, but could be possible not to overlap the keybindings came by default with ST? Thanks in advance.

**Comment by revolter** [comment]
I can't even override it!
