### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by lordn-n** [braindamageinc/SublimeHttpRequester#31]
Multiple REST calls at once, for example:

DELETE http://localhost:15672/api/queues/testing/394055ac3a814a6dba03c29335d3754d

GET http://localhost:15672/api/queues/testing

Getting:
HTTP/1.1 204 No Content
Date: Mon, 08 Dec 2014 23:22:07 GMT
Content-Type: application/json
Content-Length: 0
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
---

HTTP/1.1 204 No Content
Date: Mon, 08 Dec 2014 23:22:07 GMT
Content-Type: application/json
Content-Length: 0
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)

[{.............}]

**Comment by MarioOrtizAntoranz** [comment]
The following call:

http://localhost:3000/api/products
DELETE http://localhost:3000/api/products/56f5aca2bd58d23006a4c961
localhost:3000/api/products

Throws this response:

200 OK
X-Powered-By:Express
Content-Type:application/json; charset=utf-8
Content-Length:347
ETag:W/"15b-uG+Tom64LVBlRzjL1n8o0Q"
Date:Sat, 26 Mar 2016 12:02:12 GMT
Connection:keep-alive

Latency: 4ms
Download time:0ms


[{"_id":"56f5aca2bd58d23006a4c961","__v":0},{"_id":"56f5ae26bd58d23006a4c966","sku":"ASDF12345678","price":44.53,"__v":0,"name":"Cool product 87"},{"_id":"56f669844eb0b4de02ce1c70","name":"SUBLIME TEST","sku":"ssssssssssss","price":70,"__v":0},{"_id":"56f66bdb4eb0b4de02ce1c71","name":"Cool product 87","sku":"ASDF12345678","price":44.53,"__v":0}]

So is not deleting json object with id "56f5aca2bd58d23006a4c961"
Is there anything I am doing wrong here?
Thank you in advance.
